doctrine:
    dbal:
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
            auth_grant: App\Auth\Credential\Infrastructure\Persistence\Doctrine\Mapping\ClientGrantType
            auth_scope: App\Auth\Credential\Infrastructure\Persistence\Doctrine\Mapping\ClientScopeType
