version: "3.9"
services:
  webserver-auth:
    build:
      context: ${PWD}/.docker
      args:
        PHP_VERSION: 8.2
    env_file:
      - .env
    container_name: 'webserver-auth'
    restart: 'unless-stopped'
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html
      - ${PWD}/.docker/config/webserver/php.ini:/usr/local/etc/php/php.ini
      - ${PWD}/.docker/config/webserver/vhosts:/etc/apache2/sites-enabled
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_CS_FIXER_IGNORE_ENV: 1
