parameters:
    private_key: '%env(default:raw_private_key:file:OAUTH2_PRIVATE_KEY)%'
    public_key: '%env(default:raw_public_key:file:OAUTH2_PUBLIC_KEY)%'
    raw_private_key: '%env(OAUTH2_PRIVATE_KEY)%'
    raw_public_key: '%env(OAUTH2_PUBLIC_KEY)%'