Health:
    prefix: /api/health
    resource: ../src/Health/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
Auth:
    prefix: /api/auth
    resource: ../src/Auth/Credential/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
